name: medic_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.2
  path: ^1.9.0
  path_provider: ^2.1.2
  # ✅ upgrade ke 4.x — versi ini yang punya TextCellValue & CellStyle(bold)
  excel: ^4.0.6
  sqflite_common_ffi: ^2.3.0
  fl_chart: ^1.2.0
  syncfusion_flutter_datagrid: ^33.2.3
  file_picker: ^11.0.2
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
